# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.8.1+26.2
maven_group=tetro48.system

# Dependencies
fabric_api_version=0.156.0+26.2
dandelion_version=1.0.0-alpha.22+26.2
## Fabric Language Kotlin
flk_version=1.13.12+kotlin.2.4.0
## YACL (https://github.com/isXander/YetAnotherConfigLib)
yacl_version=3.9.4+26.2
## Mod Menu (https://modrinth.com/mod/modmenu/versions)
mod_menu_version = 20.0.1